@extends('create-form')
@section('form')
@method('PUT')
@include('input_readonly',['id'=>'npwp','value'=>$d->npwp,'label'=>'NPWP'])
@include('input_readonly',['id'=>'no_id_ktp','value'=>$d->no_id_ktp,'label'=>'No ID KTP'])
@include('input_readonly',['id'=>'nama_wajib_pajak','value'=>$d->nama_wajib_pajak,'label'=>'Nama Wajib Pajak'])
@include('input_readonly',['id'=>'rt','value'=>$d->rt,'label'=>'RT'])
@include('input_readonly',['id'=>'rw','value'=>$d->rw,'label'=>'RW'])
@include('input_readonly',['id'=>'alamat','value'=>$d->alamat,'label'=>'Alamat'])
@include('input_readonly',['id'=>'klu','value'=>$d->klu,'label'=>'KLU'])
@include('input_readonly',['id'=>'no','value'=>$d->no,'label'=>'No'])
@include('input_readonly',['id'=>'status','value'=>$d->status,'label'=>'Status Pembayaran'])
@include('input_readonly',['id'=>'total_bayar','value'=>number_format($d->total_bayar, 0, ',', '.'),'label'=>'Total Bayar','readonly'=>$d->status == 'Bayar sebagian' ? false : true])
@endsection